Repository kyma-incubator/api-gateway, pull requests merged in 2022-07, with the labels that each got.

#135 update codeowners
  CODEOWNERS
  Makefile
Labels: size/XS, lgtm, area/security, area/service-mesh

#134 Bump dependencies
  Makefile
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
  controllers/api_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/oathkeeper.ory.sh_rules.yaml
Labels: size/XXL, lgtm, area/security, area/service-mesh

#138 Prevent APIRule creation in case non secured HTTP is provided for jwks_urls and trusted_issuers
  api/v1alpha1/internal_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  internal/validation/helpers.go
  internal/validation/jwt.go
  internal/validation/validate_test.go
Labels: size/M, lgtm, area/security, area/service-mesh

#141 Add schema validation for jwks_urls and trusted_issuers for jwt handler
  config/crd/bases/gateway.kyma-project.io_apirules.yaml
Labels: size/S, lgtm, area/security, area/service-mesh
